# Generated by Django 3.0.8 on 2020-08-20 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date_placed']},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED'), ('AWAITING PAYMENT', 'AWAITING PAYMENT')], default='AWAITING PAYMENT', max_length=20),
        ),
    ]
