# Generated by Django 3.0.8 on 2020-08-10 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200810_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Product'),
        ),
    ]
