# Generated by Django 3.0.8 on 2020-08-20 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200820_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('bank', 'bank'), ('card', 'card')], default='card', max_length=20),
        ),
    ]
