# Generated by Django 3.0.8 on 2020-08-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='url',
        ),
        migrations.AddField(
            model_name='photo',
            name='upload',
            field=models.FileField(default='https://sstore-static.s3.amazonaws.com/static/images/no-product-image.jpg', upload_to=''),
            preserve_default=False,
        ),
    ]
