# Generated by Django 3.0.8 on 2020-08-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200820_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='product_id',
        ),
        migrations.AddField(
            model_name='photo',
            name='is_cover',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='product',
            name='photos',
        ),
        migrations.AddField(
            model_name='product',
            name='photos',
            field=models.ManyToManyField(to='core.Photo'),
        ),
    ]
