# Generated by Django 3.0.8 on 2020-08-06 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customer_rating_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',)},
        ),
    ]
