# Generated by Django 3.0.8 on 2020-08-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200820_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='upload',
            field=models.FileField(upload_to='images'),
        ),
    ]
