version: "3"

services:
  sstore:
    build: .
    working_dir: /opt/sstore
    volumes:
      - ./:/opt/sstore:cached
    env_file: .env
    depends_on:
      - db
    ports:
      - 8000:8000

  db:
    image: postgres
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - db_volume:/var/lib/postgresql/data/

volumes:
  db_volume:
